/*
  ==============================================================================

    ImageAttribute.cpp
    Created: 1 Aug 2016 5:24:38pm
    Author:  eshimizu

  ==============================================================================
*/

#include "ImageAttribute.h"

ImageDrawer::ImageDrawer(Image i) : _img(i) {
}

ImageDrawer::~ImageDrawer()
{
}

void ImageDrawer::resized()
{
}

void ImageDrawer::paint(Graphics & g)
{
  g.drawImageWithin(_img, 0, 0, getWidth(), getHeight(), RectanglePlacement::centred);
}

ImageAttribute::ImageAttribute(string name, string filepath, float weight) : HistogramAttribute(name),
  _sourceHist({}), _weight(weight)
{
  File img(filepath);
  FileInputStream in(img);

  if (in.openedOk()) {
    // load image
    PNGImageFormat pngReader;
    _originalImg = pngReader.decodeImage(in);
    _sourceImg = _originalImg.rescaled(_canonicalWidth, _canonicalHeight);

    getRecorder()->log(SYSTEM, "Loaded image for attribute " + name);
  }
  else {
    getRecorder()->log(SYSTEM, "Failed to load image for attribute " + name);
  }

  _showImgButton.setButtonText("Show Image");
  _showImgButton.setName("Show Image");
  _showImgButton.addListener(this);
  addAndMakeVisible(_showImgButton);
}

ImageAttribute::ImageAttribute(string name, Image img, float weight) : HistogramAttribute(name),
  _sourceHist({}), _weight(weight)
{
  _originalImg = img;
  _sourceImg = img.rescaled(_canonicalWidth, _canonicalHeight);

  _showImgButton.setButtonText("Show Image");
  _showImgButton.setName("Show Image");
  _showImgButton.addListener(this);
  addAndMakeVisible(_showImgButton);
}

ImageAttribute::ImageAttribute(string name, Snapshot * s, float weight) : HistogramAttribute(name),
  _sourceHist({}), _weight(weight)
{
  _originalImg = generateImage(s, getGlobalSettings()->_renderWidth, getGlobalSettings()->_renderHeight);
  _sourceImg = _originalImg.rescaled(_canonicalWidth, _canonicalHeight);

  _showImgButton.setButtonText("Show Image");
  _showImgButton.setName("Show Image");
  _showImgButton.addListener(this);
  addAndMakeVisible(_showImgButton);
}

ImageAttribute::~ImageAttribute()
{
}

double ImageAttribute::evaluateScene(Snapshot * s, Image& img)
{
  if (s->getRigData().size() == 0)
    return 0;

  if (img.getWidth() != _canonicalWidth || img.getHeight() != _canonicalHeight) {
    // in the event that the image was actually generated by an attribute with a different
    // size (which would be a bit weird) regenerate it here.
    img = generateImage(s);
  }

#ifdef SPARSE5D
  Sparse5DHistogram currentHist = getLabxyHist(img, _weight);
  double diff = currentHist.EMD(_sourceHist);
#endif
#ifdef LABXYHIST
  LabxyHistogram currentHist = getLabxyHist2(img, _n, _n, _n, 3, 3);
  double diff = currentHist.EMD(_sourceHist, _metric);
#endif

  return (100 - diff);
}

void ImageAttribute::preProcess()
{
#ifdef SPARSE5D
  _sourceHist = getLabxyHist(_sourceImg, _weight);
#endif
#ifdef LABXYHIST
  _sourceHist = getLabxyHist2(_sourceImg, _n, _n, _n, 3, 3);
#endif

  _metric = getGlobalSettings()->_metric;

  // sanity check
#ifdef SPARSE5D
  double selfDist = _sourceHist.EMD(_sourceHist);
#endif
#ifdef LABXYHIST
  double selfDist = _sourceHist.EMD(_sourceHist, _metric);
#endif
}

void ImageAttribute::resized()
{
  HistogramAttribute::resized();

  auto lbounds = getLocalBounds();
  auto top = lbounds.removeFromTop(24);

  top.removeFromRight(80);
  _showImgButton.setBounds(top.removeFromRight(80).reduced(2));
}

void ImageAttribute::buttonClicked(Button * b)
{
  HistogramAttribute::buttonClicked(b);

  if (b->getName() == "Show Image") {
    Viewport* vp = new Viewport();
    ImageDrawer* id = new ImageDrawer(_originalImg);
    id->setSize(500, 500);
    vp->setViewedComponent(id, true);
    vp->setSize(id->getWidth(), id->getHeight());

    CallOutBox::launchAsynchronously(vp, _showImgButton.getScreenBounds(), nullptr);
  }
}

Image ImageAttribute::getOriginalImage()
{
  return _originalImg;
}

double ImageAttribute::avgLabDistance(Snapshot * s)
{
  Image query = generateImage(s);
  double sum = 0;

  // compute average lab feature difference
  for (int y = 0; y < _canonicalHeight; y++) {
    for (int x = 0; x < _canonicalWidth; x++) {
      auto px = _sourceImg.getPixelAt(x, y);
      Eigen::Vector3d Lab1 = rgbToLab(px.getRed() / 255.0, px.getGreen() / 255.0, px.getBlue() / 255.0);

      auto px2 = query.getPixelAt(x, y);
      Eigen::Vector3d Lab2 = rgbToLab(px2.getRed() / 255.0, px2.getGreen() / 255.0, px2.getBlue() / 255.0);

      sum += (Lab1 - Lab2).norm();
    }
  }

  return sum / (_canonicalWidth * _canonicalHeight);
}
